// <auto-generated />
using SAOnlineMart.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SAOnlineMart.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240826214457_addProductsToDb")]
    partial class addProductsToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SAOnlineMart.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Handcrafted Jewelry"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Locally-Produced Clothing"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Art and Home Decor"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Furniture and Homeware"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Gourmet Food and Snacks"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Health and Wellness Products"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "Bespoke Accessories"
                        });
                });

            modelBuilder.Entity("SAOnlineMart.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "827349",
                            Description = "Paiting of African woman.",
                            ListPrice = 1999.0,
                            Name = "Painting",
                            Supplier = "Arckerman Artworks"
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "193674",
                            Description = "Sculpture of African woman.",
                            ListPrice = 849.0,
                            Name = "Ornament",
                            Supplier = "Chokwe Carvings"
                        },
                        new
                        {
                            Id = 3,
                            Barcode = "582913",
                            Description = "A trio of African style mask statues.",
                            ListPrice = 2500.0,
                            Name = "Masks",
                            Supplier = "Ettiene Etchings"
                        },
                        new
                        {
                            Id = 4,
                            Barcode = "746025",
                            Description = "Crescent shaped necklace.",
                            ListPrice = 475.0,
                            Name = "Necklace",
                            Supplier = "Nandi Necklaces"
                        },
                        new
                        {
                            Id = 5,
                            Barcode = "238964",
                            Description = "Ornate beaded bracelet.",
                            ListPrice = 399.0,
                            Name = "Bracelet",
                            Supplier = "Barend Beadwork"
                        },
                        new
                        {
                            Id = 6,
                            Barcode = "901758",
                            Description = "Beaded necklace with intricate charm.",
                            ListPrice = 819.0,
                            Name = "Charmed Necklace",
                            Supplier = "Japhthah Jewellers"
                        },
                        new
                        {
                            Id = 7,
                            Barcode = "364217",
                            Description = "Wooden stool with African pot atop.",
                            ListPrice = 1000.0,
                            Name = "Stool and Vase",
                            Supplier = "Francis Furnishers"
                        },
                        new
                        {
                            Id = 8,
                            Barcode = "512480",
                            Description = "Cabinet with bespoke pottery on display.",
                            ListPrice = 4899.0,
                            Name = "Showcase",
                            Supplier = "Author Artisans"
                        },
                        new
                        {
                            Id = 9,
                            Barcode = "679341",
                            Description = "Sleek couch with African style fabric.",
                            ListPrice = 3500.0,
                            Name = "Couch",
                            Supplier = "Makhubela Makers"
                        },
                        new
                        {
                            Id = 10,
                            Barcode = "453829",
                            Description = "African style blazer and pants suit.",
                            ListPrice = 2250.0,
                            Name = "Suit",
                            Supplier = "Thuso Taylors"
                        },
                        new
                        {
                            Id = 11,
                            Barcode = "720496",
                            Description = "African style gown for girls.",
                            ListPrice = 1600.0,
                            Name = "Gown",
                            Supplier = "Emma Embroiders"
                        },
                        new
                        {
                            Id = 12,
                            Barcode = "185237",
                            Description = "Bespoke cascading Africa dress.",
                            ListPrice = 2900.0,
                            Name = "Dress",
                            Supplier = "Felicia Fashioners"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
