using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SAOnlineMart.DataAccess.Migrations
{
    /// <inheritdoc />
    public partial class updateProductDescriptionsAgain : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "Products",
                keyColumn: "Id",
                keyValue: 6,
                column: "Description",
                value: "“<strong> Heart of the Savannah </strong>” is a stunning beaded necklace crafted by the talented artisans at Japhthah Jewellers.This exquisite piece embodies the spirit of South African artistry, with each bead meticulously selected to represent the diverse hues found in the vast landscapes, from the golden sunrise over Kruger Park to the deep umbers of its fertile earth.<br><br> The central <strong>heart-shaped charm</strong> is a true masterpiece, inspired by traditional Zulu love letters. These intricate patterns convey messages through their designs, with each twist and turn telling tales of enduring bonds and communal unity. The necklace’s multiple strands transition in color from light to dark, symbolizing the journey from dawn to dusk across the African plains.<br><br> Japhthah Jewellers, a family-run business nestled in the heart of Pretoria, has been preserving the rich heritage of South African beadwork for generations. Their artisans are known for their dedication to traditional techniques, passed down through the ages, while infusing each piece with a contemporary flair. The <strong>“Heart of the Savannah”</strong> is not just jewelry; it’s a wearable story that carries within it centuries-old techniques and the vibrant culture of South Africa.<br><br> Adorn yourself with this unique piece and feel the connection to the land and its people, celebrating the beauty and resilience of African artistry.");

            migrationBuilder.UpdateData(
                table: "Products",
                keyColumn: "Id",
                keyValue: 7,
                column: "Description",
                value: "“<strong> Chieftain’s Stooled Water Pot </strong>” by E Francis Furnishers is a captivating piece of display furniture that embodies the essence of South African tradition and artistry.This beautifully crafted African pot, resting on a rustic wooden stool,draws inspiration from the traditional drinking pots used by village chiefs, symbolizing leadership and community.<br><br> E Francis Furnishers, a renowned collective based in the heart of Limpopo, has been preserving the art of traditional pottery for generations. Founded by the visionary artisan Emmanuel Francis, the workshop is dedicated to capturing the rich cultural heritage of South Africa. Emmanuel’s passion for his craft is evident in every piece, as he infuses each creation with a deep love for his homeland’s history and traditions.<br><br> The <strong>“Chieftain’s Stooled Water Pot”</strong> is crafted from the rich, red earth of the region, known for its fertile soil and abundant natural resources. The intricate patterns and designs etched into the pot’s surface are inspired by ancient tribal motifs, each symbol carrying a story of its own. The geometric shapes and earthy tones reflect the beauty of the South African landscape, from the rolling hills to the vast savannahs.<br><br> This pot is more than just a decorative item; it is a piece of living history, a tangible connection to the past. The artisans at E Francis Furnishers use traditional techniques passed down through generations, ensuring that each piece is a true work of art. The wooden stool, with its simple yet elegant design, complements the pot perfectly, adding a touch of rustic charm to any space.<br><br> The <strong>“Chieftain’s Stooled Water Pot”</strong> is a celebration of South African culture and craftsmanship. Each line and curve tells a story of resilience and beauty, reflecting the spirit of the people who create these masterpieces. Displaying this pot in your home invites not only an aesthetic transformation but also an immersive cultural experience. It is a bridge to a world where every creation is infused with meaning and every artifact sings the song of its people.<br><br> Bring home this rustic embodiment of South African artisanship and let your space narrate stories that transcend time.");

            migrationBuilder.UpdateData(
                table: "Products",
                keyColumn: "Id",
                keyValue: 8,
                column: "Description",
                value: "“<strong> Amphora Collection </strong>” by Arthur Artisans is a stunning showcase of South African craftsmanship.This elegant wooden cabinet, adorned with intricate geometric carvings, houses an array of vases that each tell a unique story of tradition and artistry.<br><br> Arthur Artisans, led by the talented Arthur Stemmet, has been a cornerstone of Cape Town’s artisanal community for over three decades. Arthur’s passion for preserving the rich cultural heritage of South Africa is evident in every piece he creates. Drawing inspiration from the rolling hills and vibrant flora of the Western Cape, Arthur infuses his work with a deep love for his homeland’s diverse culture and landscape.<br><br> The <strong>“Amphora Collection”</strong> features vases of various shapes, sizes, and designs, each crafted with meticulous attention to detail. The natural color palette, ranging from earthy browns to soft creams, reflects the beauty of the South African landscape. The intricate patterns and textures on the vases pay homage to ancient African pottery techniques passed down through generations.<br><br> These vases are not just decorative items; they are keepers of history, artfully molded by hands that understand the value of preserving culture in every curve and etching. Displaying this collection in your home invites not only an aesthetic transformation but also an immersive cultural experience.<br><br> The <strong>“Amphora Collection”</strong> is more than just a set of vases—it’s a celebration of South African heritage, a testament to the enduring legacy of traditional craftsmanship, and a bridge to a world where every creation is infused with meaning and every artifact sings the song of its people. Bring home this rustic embodiment of South African artisanship and let your space narrate stories that transcend time.");

            migrationBuilder.UpdateData(
                table: "Products",
                keyColumn: "Id",
                keyValue: 9,
                column: "Description",
                value: "“<strong> Heritage Haven </strong>” by Makhubela Makers is a testament to the rich cultural tapestry of South Africa.This three - seater couch, adorned with intricate African - inspired fabric, is a blend of modern design and traditional craftsmanship.<br><br> Makhubela Makers, a family-run workshop in Pretoria, has been a beacon of South African artistry for over three decades. Founded by Thabo Makhubela, the workshop draws inspiration from the diverse landscapes and vibrant cultures of the region. Thabo’s passion for preserving traditional techniques while infusing contemporary elements is evident in every piece they create.<br><br> The <strong>“Heritage Haven”</strong> couch features a sleek, modern silhouette that beautifully contrasts with the detailed patterns and textures of the fabric. The geometric designs and earthy tones are reminiscent of the vast African plains, capturing the essence of the land and its people. Each stitch is a tribute to the meticulous craftsmanship and cultural significance embedded in the fabric, sourced from local weavers who have honed their skills over generations.<br><br> This couch is not just a piece of furniture; it’s a narrative woven into existence by skilled hands. It invites you to experience the stories and traditions of South Africa, offering a comfortable and culturally rich addition to any living space. With <strong>“Heritage Haven”</strong>, you bring home a piece of South African heritage, celebrating the beauty and resilience of its artistry.");

            migrationBuilder.UpdateData(
                table: "Products",
                keyColumn: "Id",
                keyValue: 10,
                columns: new[] { "Description", "ImageUrl" },
                values: new object[] { "“<strong> Zulu Elegance Ensemble </strong>” by Thuso Taylors is a sartorial masterpiece that captures the essence of South African heritage and modern sophistication. This men’s suit, with its intricate patterns and vibrant colors, is a testament to the skilled craftsmanship and cultural richness of the region.<br><br>Thuso Taylors, a distinguished atelier based in Johannesburg, has been at the forefront of South African fashion for over two decades. Founded by the visionary designer Thuso Mokoena, the atelier draws inspiration from the diverse cultures and landscapes of South Africa. Thuso’s designs are renowned for their fusion of traditional motifs with contemporary silhouettes, creating pieces that are both timeless and modern.<br><br> The <strong>“Zulu Elegance Ensemble”</strong> features a tailored suit with patterns inspired by ancient Zulu art. The geometric shapes and bold colors reflect the vibrant energy of South African culture, from the rhythmic beats of traditional music to the dynamic movements of Zulu dance. The suit’s earthy tones, accented by pops of color, evoke the natural beauty of the African landscape, from the golden savannahs to the lush valleys.<br><br> This suit is more than just attire; it is a celebration of South African artistry brought to life through fashion. Each stitch tells a story of tradition and innovation, as local artisans meticulously weave cultural narratives into the fabric. The suit’s design pays homage to the rich history of the Zulu people, while also embracing the modern gentleman’s need for style and substance.<br><br> Wearing the <strong>“Zulu Elegance Ensemble”</strong> is an invitation to embrace the beauty and resilience of South African culture. Each design element is a tribute to the artisans who have mastered their craft over generations, echoing their connection to nature and community. This suit is a statement piece that carries within it the stories and traditions of South Africa, making every occasion a celebration of heritage and elegance.", "\\images\\product\\a60ea39c-e9fa-4e92-84a3-6e20387e8a62.webp" });

            migrationBuilder.UpdateData(
                table: "Products",
                keyColumn: "Id",
                keyValue: 11,
                column: "Description",
                value: "“<strong> Little Safari Dream Dress </strong>” by Emma Embroiders is a delightful blend of tradition and whimsy, perfect for the young adventurer. This charming children’s dress features intricate embroidery that tells a story of South African heritage and craftsmanship.<br><br>Emma Embroiders, a beloved atelier based in the vibrant city of Durban, has been creating beautiful, handcrafted garments for over two decades. Founded by Emma Ndlovu, the atelier is renowned for its dedication to preserving traditional embroidery techniques while infusing each piece with contemporary flair. Emma’s passion for her craft is evident in every stitch, as she draws inspiration from the rich cultural tapestry of South Africa.<br><br> The <strong>“Little Safari Dream Dress”</strong> is adorned with vibrant patterns and traditional African motifs, each symbol carrying a story of its own. The geometric shapes and earthy tones are reminiscent of the diverse landscapes and wildlife of the African plains. The dress is made from high-quality, comfortable fabric, ensuring that your little one can explore the world in style and comfort.<br><br> This dress is more than just clothing; it’s a piece of wearable art that celebrates the beauty and resilience of South African culture. Each design element is a tribute to the artisans who have mastered their craft over generations, echoing their connection to nature and community. The <strong>“Little Safari Dream Dress”</strong> invites your child to embark on a journey of discovery, wrapped in the stories and traditions of South Africa.");

            migrationBuilder.UpdateData(
                table: "Products",
                keyColumn: "Id",
                keyValue: 12,
                column: "Description",
                value: "“<strong> Sunset Serenade Gown </strong>” by Felicia Fashioners is a vibrant celebration of South African elegance and tradition. This full-length, strapless dress features a voluminous skirt adorned with intricate patterns in shades of red, yellow, gold, and brown, reminiscent of the breathtaking hues of an African sunset.<br><br>Felicia Fashioners, a boutique atelier based in the heart of Cape Town, has been a beacon of South African haute couture for over two decades. Founded by the visionary designer Felicia Maseko, the atelier draws inspiration from the rich cultural heritage and diverse landscapes of South Africa. Felicia’s designs are renowned for their fusion of traditional motifs with contemporary silhouettes, creating pieces that are both timeless and modern.<br><br> The <strong>“Sunset Serenade Gown”</strong> is a testament to this unique blend. The geometric and organic shapes in the fabric are inspired by ancient tribal art, each symbol carrying a story of its own. The bold colors reflect the vibrant energy of local markets and the natural beauty of the African plains. The gown’s voluminous skirt and strapless bodice create a silhouette that is both dramatic and elegant, perfect for making a statement at any event.<br><br> This gown is not just a piece of clothing; it’s a work of art that embodies the spirit of South Africa. Each stitch is a tribute to the artisans who have mastered their craft over generations, echoing their connection to nature and community. Wearing the <strong>“Sunset Serenade Gown”</strong> is an invitation to embrace the rich tapestry of South African culture and style, making every occasion a celebration of heritage and beauty.");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "Products",
                keyColumn: "Id",
                keyValue: 6,
                column: "Description",
                value: "“< strong > Heart of the Savannah </ strong >” is a stunning beaded necklace crafted by the talented artisans at Japhthah Jewellers.This exquisite piece embodies the spirit of South African artistry, with each bead meticulously selected to represent the diverse hues found in the vast landscapes, from the golden sunrise over Kruger Park to the deep umbers of its fertile earth.<br><br> The central <strong>heart-shaped charm</strong> is a true masterpiece, inspired by traditional Zulu love letters. These intricate patterns convey messages through their designs, with each twist and turn telling tales of enduring bonds and communal unity. The necklace’s multiple strands transition in color from light to dark, symbolizing the journey from dawn to dusk across the African plains.<br><br> Japhthah Jewellers, a family-run business nestled in the heart of Pretoria, has been preserving the rich heritage of South African beadwork for generations. Their artisans are known for their dedication to traditional techniques, passed down through the ages, while infusing each piece with a contemporary flair. The <strong>“Heart of the Savannah”</strong> is not just jewelry; it’s a wearable story that carries within it centuries-old techniques and the vibrant culture of South Africa.<br><br> Adorn yourself with this unique piece and feel the connection to the land and its people, celebrating the beauty and resilience of African artistry.");

            migrationBuilder.UpdateData(
                table: "Products",
                keyColumn: "Id",
                keyValue: 7,
                column: "Description",
                value: "“< strong > Chieftain’s Stooled Water Pot </ strong >” by E Francis Furnishers is a captivating piece of display furniture that embodies the essence of South African tradition and artistry.This beautifully crafted African pot, resting on a rustic wooden stool,draws inspiration from the traditional drinking pots used by village chiefs, symbolizing leadership and community.<br><br> E Francis Furnishers, a renowned collective based in the heart of Limpopo, has been preserving the art of traditional pottery for generations. Founded by the visionary artisan Emmanuel Francis, the workshop is dedicated to capturing the rich cultural heritage of South Africa. Emmanuel’s passion for his craft is evident in every piece, as he infuses each creation with a deep love for his homeland’s history and traditions.<br><br> The <strong>“Chieftain’s Stooled Water Pot”</strong> is crafted from the rich, red earth of the region, known for its fertile soil and abundant natural resources. The intricate patterns and designs etched into the pot’s surface are inspired by ancient tribal motifs, each symbol carrying a story of its own. The geometric shapes and earthy tones reflect the beauty of the South African landscape, from the rolling hills to the vast savannahs.<br><br> This pot is more than just a decorative item; it is a piece of living history, a tangible connection to the past. The artisans at E Francis Furnishers use traditional techniques passed down through generations, ensuring that each piece is a true work of art. The wooden stool, with its simple yet elegant design, complements the pot perfectly, adding a touch of rustic charm to any space.<br><br> The <strong>“Chieftain’s Stooled Water Pot”</strong> is a celebration of South African culture and craftsmanship. Each line and curve tells a story of resilience and beauty, reflecting the spirit of the people who create these masterpieces. Displaying this pot in your home invites not only an aesthetic transformation but also an immersive cultural experience. It is a bridge to a world where every creation is infused with meaning and every artifact sings the song of its people.<br><br> Bring home this rustic embodiment of South African artisanship and let your space narrate stories that transcend time.");

            migrationBuilder.UpdateData(
                table: "Products",
                keyColumn: "Id",
                keyValue: 8,
                column: "Description",
                value: "“< strong > Amphora Collection </ strong >” by Arthur Artisans is a stunning showcase of South African craftsmanship.This elegant wooden cabinet, adorned with intricate geometric carvings, houses an array of vases that each tell a unique story of tradition and artistry.<br><br> Arthur Artisans, led by the talented Arthur Stemmet, has been a cornerstone of Cape Town’s artisanal community for over three decades. Arthur’s passion for preserving the rich cultural heritage of South Africa is evident in every piece he creates. Drawing inspiration from the rolling hills and vibrant flora of the Western Cape, Arthur infuses his work with a deep love for his homeland’s diverse culture and landscape.<br><br> The <strong>“Amphora Collection”</strong> features vases of various shapes, sizes, and designs, each crafted with meticulous attention to detail. The natural color palette, ranging from earthy browns to soft creams, reflects the beauty of the South African landscape. The intricate patterns and textures on the vases pay homage to ancient African pottery techniques passed down through generations.<br><br> These vases are not just decorative items; they are keepers of history, artfully molded by hands that understand the value of preserving culture in every curve and etching. Displaying this collection in your home invites not only an aesthetic transformation but also an immersive cultural experience.<br><br> The <strong>“Amphora Collection”</strong> is more than just a set of vases—it’s a celebration of South African heritage, a testament to the enduring legacy of traditional craftsmanship, and a bridge to a world where every creation is infused with meaning and every artifact sings the song of its people. Bring home this rustic embodiment of South African artisanship and let your space narrate stories that transcend time.");

            migrationBuilder.UpdateData(
                table: "Products",
                keyColumn: "Id",
                keyValue: 9,
                column: "Description",
                value: "“< strong > Heritage Haven </ strong >” by Makhubela Makers is a testament to the rich cultural tapestry of South Africa.This three - seater couch, adorned with intricate African - inspired fabric, is a blend of modern design and traditional craftsmanship.<br><br> Makhubela Makers, a family-run workshop in Pretoria, has been a beacon of South African artistry for over three decades. Founded by Thabo Makhubela, the workshop draws inspiration from the diverse landscapes and vibrant cultures of the region. Thabo’s passion for preserving traditional techniques while infusing contemporary elements is evident in every piece they create.<br><br> The <strong>“Heritage Haven”</strong> couch features a sleek, modern silhouette that beautifully contrasts with the detailed patterns and textures of the fabric. The geometric designs and earthy tones are reminiscent of the vast African plains, capturing the essence of the land and its people. Each stitch is a tribute to the meticulous craftsmanship and cultural significance embedded in the fabric, sourced from local weavers who have honed their skills over generations.<br><br> This couch is not just a piece of furniture; it’s a narrative woven into existence by skilled hands. It invites you to experience the stories and traditions of South Africa, offering a comfortable and culturally rich addition to any living space. With <strong>“Heritage Haven”</strong>, you bring home a piece of South African heritage, celebrating the beauty and resilience of its artistry.");

            migrationBuilder.UpdateData(
                table: "Products",
                keyColumn: "Id",
                keyValue: 10,
                columns: new[] { "Description", "ImageUrl" },
                values: new object[] { "“< strong > Zulu Elegance Ensemble </ strong >” by Thuso Taylors is a sartorial masterpiece that captures the essence of South African heritage and modern sophistication. This men’s suit, with its intricate patterns and vibrant colors, is a testament to the skilled craftsmanship and cultural richness of the region.<br><br>Thuso Taylors, a distinguished atelier based in Johannesburg, has been at the forefront of South African fashion for over two decades. Founded by the visionary designer Thuso Mokoena, the atelier draws inspiration from the diverse cultures and landscapes of South Africa. Thuso’s designs are renowned for their fusion of traditional motifs with contemporary silhouettes, creating pieces that are both timeless and modern.<br><br> The <strong>“Zulu Elegance Ensemble”</strong> features a tailored suit with patterns inspired by ancient Zulu art. The geometric shapes and bold colors reflect the vibrant energy of South African culture, from the rhythmic beats of traditional music to the dynamic movements of Zulu dance. The suit’s earthy tones, accented by pops of color, evoke the natural beauty of the African landscape, from the golden savannahs to the lush valleys.<br><br> This suit is more than just attire; it is a celebration of South African artistry brought to life through fashion. Each stitch tells a story of tradition and innovation, as local artisans meticulously weave cultural narratives into the fabric. The suit’s design pays homage to the rich history of the Zulu people, while also embracing the modern gentleman’s need for style and substance.<br><br> Wearing the <strong>“Zulu Elegance Ensemble”</strong> is an invitation to embrace the beauty and resilience of South African culture. Each design element is a tribute to the artisans who have mastered their craft over generations, echoing their connection to nature and community. This suit is a statement piece that carries within it the stories and traditions of South Africa, making every occasion a celebration of heritage and elegance.", "" });

            migrationBuilder.UpdateData(
                table: "Products",
                keyColumn: "Id",
                keyValue: 11,
                column: "Description",
                value: "“< strong > Little Safari Dream Dress </ strong >” by Emma Embroiders is a delightful blend of tradition and whimsy, perfect for the young adventurer. This charming children’s dress features intricate embroidery that tells a story of South African heritage and craftsmanship.<br><br>Emma Embroiders, a beloved atelier based in the vibrant city of Durban, has been creating beautiful, handcrafted garments for over two decades. Founded by Emma Ndlovu, the atelier is renowned for its dedication to preserving traditional embroidery techniques while infusing each piece with contemporary flair. Emma’s passion for her craft is evident in every stitch, as she draws inspiration from the rich cultural tapestry of South Africa.<br><br> The <strong>“Little Safari Dream Dress”</strong> is adorned with vibrant patterns and traditional African motifs, each symbol carrying a story of its own. The geometric shapes and earthy tones are reminiscent of the diverse landscapes and wildlife of the African plains. The dress is made from high-quality, comfortable fabric, ensuring that your little one can explore the world in style and comfort.<br><br> This dress is more than just clothing; it’s a piece of wearable art that celebrates the beauty and resilience of South African culture. Each design element is a tribute to the artisans who have mastered their craft over generations, echoing their connection to nature and community. The <strong>“Little Safari Dream Dress”</strong> invites your child to embark on a journey of discovery, wrapped in the stories and traditions of South Africa.");

            migrationBuilder.UpdateData(
                table: "Products",
                keyColumn: "Id",
                keyValue: 12,
                column: "Description",
                value: "“< strong > Sunset Serenade Gown </ strong >” by Felicia Fashioners is a vibrant celebration of South African elegance and tradition. This full-length, strapless dress features a voluminous skirt adorned with intricate patterns in shades of red, yellow, gold, and brown, reminiscent of the breathtaking hues of an African sunset.<br><br>Felicia Fashioners, a boutique atelier based in the heart of Cape Town, has been a beacon of South African haute couture for over two decades. Founded by the visionary designer Felicia Maseko, the atelier draws inspiration from the rich cultural heritage and diverse landscapes of South Africa. Felicia’s designs are renowned for their fusion of traditional motifs with contemporary silhouettes, creating pieces that are both timeless and modern.<br><br> The <strong>“Sunset Serenade Gown”</strong> is a testament to this unique blend. The geometric and organic shapes in the fabric are inspired by ancient tribal art, each symbol carrying a story of its own. The bold colors reflect the vibrant energy of local markets and the natural beauty of the African plains. The gown’s voluminous skirt and strapless bodice create a silhouette that is both dramatic and elegant, perfect for making a statement at any event.<br><br> This gown is not just a piece of clothing; it’s a work of art that embodies the spirit of South Africa. Each stitch is a tribute to the artisans who have mastered their craft over generations, echoing their connection to nature and community. Wearing the <strong>“Sunset Serenade Gown”</strong> is an invitation to embrace the rich tapestry of South African culture and style, making every occasion a celebration of heritage and beauty.");
        }
    }
}
